### PR TITLE
Add ruby 2.5 version

### PR DESCRIPTION
**Pull request by ouranos**
* Add ruby 2.5 image (based on stretch)
* Moved shared files

:warning: The docker cloud build config will need to be changed before merging :warning:

### CODE REVIEW

**Review by alachaum — APPROVED** [review]
👍

**Comment by ouranos** [comment]
Got accidentally closed while renaming `v1.0` to `1.0`

**Comment by ouranos** [comment]
Docker cloud build config updated:
image

I'll disable the old branches once the build is confirmed to be working

**Comment by ouranos** [comment]
Building: 
image

**Pull request merged**
